# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Backend CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./codebase/backend/package.json
    - run: npm install
      working-directory: ./codebase/backend
      name: Installing standard dependencies
    - run: npm install --only=dev
      working-directory: ./codebase/backend
      name: Installing dev dependencies
    - run: npm run start-bg
      working-directory: ./codebase/backend
      name: Start Express.js server
    - run: npm run test
      working-directory: ./codebase/backend
      name: Run tests
